# Generated by Django 5.1.1 on 2024-11-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
