# Generated by Django 5.1.1 on 2024-12-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_orderitem_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_payment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
