# Generated by Django 5.1.1 on 2024-12-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_paypal_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paypal_payment_status',
        ),
    ]
