# Generated by Django 5.1.1 on 2024-10-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_delete_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customuser',
        ),
    ]
