# Generated by Django 5.1.1 on 2024-10-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    def set_default_role(apps, schema_editor):
        Customuser = apps.get_model('ecommerce', 'Customuser')
        print(Customuser)
        Customuser.objects.filter(role__isnull=True).update(role='customer')  # or 'seller'



    dependencies = [
        ('ecommerce', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.RunPython(set_default_role),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller')], default='customer', max_length=50),
        ),
    ]
