# Generated by Django 5.1.1 on 2024-11-21 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_seller_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
