# Generated by Django 5.1.1 on 2024-11-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_alter_seller_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_name',
            field=models.CharField(max_length=100),
        ),
    ]
